src/Entity/User.php
<?php

declare(strict_types=1);

namespace App\Entity;

use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    private int $id;
    private string $email;
    private ?string $password;
    private array $roles = [];

    public function __construct(
        string $email,
        array $roles = []
    ) {
        $this->email = $email;
        $this->roles = $roles;
    }

    public function getId(): int
    {
        return $this->id;
    }

    public function getUserIdentifier(): string
    {
        return $this->email;
    }

    public function getRoles(): array
    {
        $roles = $this->roles;
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setHashedPassword(string $hashedPassword): void
    {
        $this->password = $hashedPassword;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function eraseCredentials()
    {
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>{% block title %}Welcome!{% endblock %}</title>
    {# Run `composer require symfony/webpack-encore-bundle`
    and uncomment the following Encore helpers to start using Symfony UX #}
    {% block stylesheets %}
    {#{{ encore_entry_link_tags('app') }}#}
    <link rel="stylesheet" href="{{ asset('css/bootstrap.css') }}" />
    {% endblock %}

    {% block javascripts %}
    {#{{ encore_entry_script_tags('app') }}#}
    {% endblock %}
  </head>
  <body>
    {% block menu %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Dinosaurs</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            {% if app.user is not null %}
              <li class="nav-item">
                <a
                  class="nav-link{% if app.request.get('_route') == 'app_list_dinosaurs' %} active{% endif %}"
                  aria-current="page"
                  href="{{ path('app_list_dinosaurs') }}"
                >
                  Dinosaurs list
                </a>
              </li>
              {% if 'ROLE_ADMIN' in app.user.roles %}
                <li class="nav-item">
                  <a 
                    class="nav-link{% if app.request.get('_route') == 'app_create_dinosaur' %} active{% endif %}" 
                    href="{{ path('app_create_dinosaur') }}"
                  >
                    Create a dinosaur
                  </a>
                </li>
              {% endif %}
              <li class="nav-item">
                <a 
                  class="nav-link{% if app.request.get('_route') == 'app_list_species' %} active{% endif %}"
                  aria-current="page"
                  href="{{ path('app_list_species') }}"
                >
                  Species list
                </a>
              </li>
              {% if 'ROLE_ADMIN' in app.user.roles %}
                <li class="nav-item">
                  <a 
                    class="nav-link{% if app.request.get('_route') == 'app_create_species' %} active{% endif %}" 
                    href="{{ path('app_create_species') }}"
                  >
                    Create a species
                  </a>
                </li>
              {% endif %}
              <li class="nav-item">
                <a 
                  class="nav-link{% if app.request.get('_route') == 'app_create_species' %} active{% endif %}" 
                  href="{{ path('logout') }}"
                >
                  Logout
                </a>
              </li>
            {% else %}
              <li class="nav-item">
                <a 
                  class="nav-link{% if app.request.get('_route') == 'app_list_species' %} active{% endif %}"
                  aria-current="page"
                  href="{{ path('register') }}"
                >
                  Register
                </a>
              </li>
              <li class="nav-item">
                <a 
                  class="nav-link{% if app.request.get('_route') == 'app_create_species' %} active{% endif %}" 
                  href="{{ path('login') }}"
                >
                  Login
                </a>
              </li>
            {% endif %}
          </ul>

            {% if searchForm is defined %}
              {{ form_start(searchForm, { 'attr': {'class': 'd-flex'}}) }}
                {{ form_widget(searchForm.q) }}
                {{ form_widget(searchForm.submit) }}
              {{ form_end(searchForm) }}
            {% endif %}

            {% if app.user is not null %}
              <span class="navbar-text ms-2">
                {{ app.user.userIdentifier }}
              </span>
            {% endif %}
        </div>
      </div>
    </nav>
    {% endblock %}

    {% block flashMessage %}
      {% if app.session.flashbag.peekAll %}
      <div id="container">
        {% for name, messages in app.session.flashbag.all %}
          {% for message in messages %}
          <div class="alert alert-{{ name }}">
            {{ message }}
          </div>
          {% endfor %}
        {% endfor %}
      </div>
      {% endif %}
    {% endblock %}

    {% block body %}{% endblock %}
  </body>
</html>

templates/create-dinosaur.html.twig
{% extends 'base.html.twig' %}

{% block title %}Create a dinosaur{% endblock %}

{% block body %}
<main class="w-25 p-3">
  <h1>Create a dinosaur</h1>

  {{ form(form) }}
</main>
{% endblock %}

templates/create-species.html.twig
{% extends 'base.html.twig' %}

{% block title %}Create a species{% endblock %}

{% block body %}
<main class="w-25 p-3">
  <h1>Create a species</h1>

  {{ form(form) }}
</main>
{% endblock %}

templates/dinosaur.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ dinosaur.name }}{% endblock %}

{% block stylesheets %}
{{ parent() }}
<link rel="stylesheet" href="{{ asset('css/dinosaurs.css') }}" />
{% endblock %}

{% block javascripts  %}
<script src="{{ asset('js/bootstrap.min.js') }}"></script>
{% endblock %}

{% block body %}
<main>
  <header>
    <a href="{{ path('app_list_dinosaurs') }}">
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-arrow-left" viewBox="0 0 16 16">
        <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z"/>
      </svg>
    </a>
    <h1>{{ dinosaur.name }}</h1>
  </header>
  <section>
    <img src="{{ asset('img/dino.png') }}" alt="twbs" class="rounded-circle flex-shrink-0">
    <div>
      <p>
        {% if dinosaur.gender == 'Male' %}
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-gender-male" viewBox="0 0 16 16">
          <path fill-rule="evenodd" d="M9.5 2a.5.5 0 0 1 0-1h5a.5.5 0 0 1 .5.5v5a.5.5 0 0 1-1 0V2.707L9.871 6.836a5 5 0 1 1-.707-.707L13.293 2H9.5zM6 6a4 4 0 1 0 0 8 4 4 0 0 0 0-8z"/>
        </svg>
        &nbsp; Male
        {% elseif dinosaur.gender == 'Female' %}
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-gender-female" viewBox="0 0 16 16">
          <path fill-rule="evenodd" d="M8 1a4 4 0 1 0 0 8 4 4 0 0 0 0-8zM3 5a5 5 0 1 1 5.5 4.975V12h2a.5.5 0 0 1 0 1h-2v2.5a.5.5 0 0 1-1 0V13h-2a.5.5 0 0 1 0-1h2V9.975A5 5 0 0 1 3 5z"/>
        </svg>
        &nbsp; Female
        {% else %}
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-gender-ambiguous" viewBox="0 0 16 16">
          <path fill-rule="evenodd" d="M11.5 1a.5.5 0 0 1 0-1h4a.5.5 0 0 1 .5.5v4a.5.5 0 0 1-1 0V1.707l-3.45 3.45A4 4 0 0 1 8.5 10.97V13H10a.5.5 0 0 1 0 1H8.5v1.5a.5.5 0 0 1-1 0V14H6a.5.5 0 0 1 0-1h1.5v-2.03a4 4 0 1 1 3.471-6.648L14.293 1H11.5zm-.997 4.346a3 3 0 1 0-5.006 3.309 3 3 0 0 0 5.006-3.31z"/>
        </svg>
        &nbsp; {{dinosaur.gender}}
        {% endif %}
      </p>
      <p>
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-calendar3" viewBox="0 0 16 16">
          <path d="M14 0H2a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2zM1 3.857C1 3.384 1.448 3 2 3h12c.552 0 1 .384 1 .857v10.286c0 .473-.448.857-1 .857H2c-.552 0-1-.384-1-.857V3.857z"/>
          <path d="M6.5 7a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm-9 3a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm-9 3a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2z"/>
        </svg>
        &nbsp; {{ dinosaur.age }} years old
      </p>
      <p>
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bug" viewBox="0 0 16 16">
          <path d="M4.355.522a.5.5 0 0 1 .623.333l.291.956A4.979 4.979 0 0 1 8 1c1.007 0 1.946.298 2.731.811l.29-.956a.5.5 0 1 1 .957.29l-.41 1.352A4.985 4.985 0 0 1 13 6h.5a.5.5 0 0 0 .5-.5V5a.5.5 0 0 1 1 0v.5A1.5 1.5 0 0 1 13.5 7H13v1h1.5a.5.5 0 0 1 0 1H13v1h.5a1.5 1.5 0 0 1 1.5 1.5v.5a.5.5 0 1 1-1 0v-.5a.5.5 0 0 0-.5-.5H13a5 5 0 0 1-10 0h-.5a.5.5 0 0 0-.5.5v.5a.5.5 0 1 1-1 0v-.5A1.5 1.5 0 0 1 2.5 10H3V9H1.5a.5.5 0 0 1 0-1H3V7h-.5A1.5 1.5 0 0 1 1 5.5V5a.5.5 0 0 1 1 0v.5a.5.5 0 0 0 .5.5H3c0-1.364.547-2.601 1.432-3.503l-.41-1.352a.5.5 0 0 1 .333-.623zM4 7v4a4 4 0 0 0 3.5 3.97V7H4zm4.5 0v7.97A4 4 0 0 0 12 11V7H8.5zM12 6a3.989 3.989 0 0 0-1.334-2.982A3.983 3.983 0 0 0 8 2a3.983 3.983 0 0 0-2.667 1.018A3.989 3.989 0 0 0 4 6h8z"/>
        </svg>
        &nbsp; {{ dinosaur.species.name }}
      </p>
      <p>
        Eyes color&nbsp;
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="{{ dinosaur.eyesColor }}" class="bi bi-eye-fill" viewBox="0 0 16 16">
          <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0z"/>
          <path d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8zm8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7z"/>
        </svg>
      </p>
      <a href="{{ path('app_edit_dinosaur', {id: dinosaur.id}) }}" class="btn btn-primary">Edit</a>
      <a href="{{ path('app_remove_dinosaur', {id: dinosaur.id}) }}" class="btn btn-danger">Remove</a>
    </div>
  </section>
</main>
{% endblock %}

templates/dinosaurs-list.html.twig
{% extends 'base.html.twig' %}

{% block title %}Dinosaurs{% endblock %}

{% block stylesheets %}
{{ parent() }}
<link rel="stylesheet" href="{{ asset('css/dinosaurs.css') }}" />
{% endblock %}

{% block javascripts  %}
<script src="{{ asset('js/bootstrap.min.js') }}"></script>
{% endblock %}

{% block body %}
<main>
  <div class="list-group">
    {% for dinosaur in dinosaurs %}
    <a class="list-group-item list-group-item-action d-flex gap-3 py-3"
      href="{{ path('app_single_dinosaur', {id: dinosaur.id}) }}"
    >
      <img
      src="{{ asset('img/dino.png') }}" 
      alt="twbs" 
      width="32" 
      height="32" 
      class="rounded-circle flex-shrink-0"
      >
      <div class="d-flex gap-2 w-100 justify-content-between">
        {{ dinosaur.name }}
      </div>
    </a>
    {% endfor %}
  </div>
</main>
{% endblock %}

templates/edit-dinosaur.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit a dinosaur{% endblock %}

{% block body %}
<main class="w-25 p-3">
  <h1>Edit a dinosaur</h1>

  {{ form(form) }}
</main>
{% endblock %}

templates/edit-species.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit a species{% endblock %}

{% block body %}
<main class="w-25 p-3">
  <h1>Edit a species</h1>

  {{ form(form) }}
</main>
{% endblock %}

templates/login.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {% if error %}
        <div>{{ error.messageKey|trans(error.messageData, 'security') }}</div>
    {% endif %}

    <div class="container">
        <div class="row py-4">
            <div class="col-md-6 offset-2">
                <form action="{{ path('login') }}" method="post">
                    <label for="username" class="form-label">Email:</label>
                    <input type="text" id="username" class="form-control" name="_username" value="{{ last_username }}"/>

                    <label for="password" class="form-label">Password:</label>
                    <input type="password" class="form-control" id="password" name="_password"/>
                    
                    <div class="d-grid gap-2 col-6 mx-auto py-3">
                        <button type="submit" class="btn btn-primary">Login</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/register.html.twig
{% extends 'base.html.twig' %}

{% block title %}Register{% endblock %}

{% block body %}
<main class="w-25 p-3">
  <h1>Register</h1>

  {{ form(form) }}
</main>
{% endblock %}

templates/species-list.html.twig
{% extends 'base.html.twig' %}

{% block title %}Species{% endblock %}

{% block stylesheets %}
{{ parent() }}
<link rel="stylesheet" href="{{ asset('css/dinosaurs.css') }}" />
{% endblock %}

{% block body %}
<main>
  <div class="list-group">
    {% for species in speciesList %}
    <a class="list-group-item list-group-item-action d-flex gap-3 py-3"
      href="{{ path('app_edit_species', {id: species.id}) }}"
    >
      <img
      src="{{ asset('img/dino.png') }}" 
      alt="twbs" 
      width="32" 
      height="32" 
      class="rounded-circle flex-shrink-0"
      >
      <div class="d-flex gap-2 w-100 justify-content-between">
        {{ species.name }}
      </div>
    </a>
    {% endfor %}
  </div>
</main>
{% endblock %}